import click
import pyvista as pv
import logging
from pathlib import Path
import re

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

@click.command()
@click.argument("case_dir", type=click.Path(exists=True, path_type=Path))
@click.argument("output_dir", type=click.Path(path_type=Path))
def visualize_vtk(case_dir: Path, output_dir: Path):
    """
    Generate visualizations from OpenFOAM VTK output (generated by foamToVTK).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    
    vtk_dir = case_dir / "VTK"
    if not vtk_dir.exists():
        logging.warning(f"VTK directory not found in {case_dir}. Run foamToVTK first.")
        return

    # Find global mesh files: case_name_TIME.vtk
    # e.g., wigley_0.vtk
    vtk_files = list(vtk_dir.glob("*_*.vtk"))
    
    # Filter out patch files (usually in subdirs or named differently, foamToVTK puts internal mesh in root of VTK/)
    # Actually foamToVTK puts them in VTK/case_time.vtk. Patches are in VTK/patchName/
    
    valid_files = []
    for f in vtk_files:
        # Extract time
        match = re.search(r"_([0-9\.]+)\.vtk$", f.name)
        if match:
             valid_files.append((float(match.group(1)), f))
    
    if not valid_files:
        logging.warning("No valid VTK time steps found.")
        return

    # Sort by time, get latest
    latest_time, latest_file = max(valid_files, key=lambda x: x[0])
    logging.info(f"Visualizing VTK results from time: {latest_time} ({latest_file.name})")

    try:
        mesh = pv.read(latest_file)
        
        p = pv.Plotter(off_screen=True)
        p.add_mesh(mesh, show_edges=False, color="white", opacity=0.3, label="Domain")
        
        # Visualize Alpha Water (Iso-surface)
        if "alpha.water" in mesh.point_data:
            water = mesh.contour(isosurfaces=[0.5], scalars="alpha.water")
            p.add_mesh(water, color="blue", opacity=0.9, specular=0.5, label="Water Surface")
        else:
             logging.warning("alpha.water not found in VTK data.")

        # Visualize Hull (if patch exists)
        hull_dir = vtk_dir / "hull"
        if hull_dir.exists():
             hull_files = list(hull_dir.glob(f"*_{int(latest_time) if latest_time.is_integer() else latest_time}.vtk"))
             # Match time loosely if exact match fails? foamToVTK matches accurately.
             # Actually foamToVTK uses loose naming sometimes? e.g. hull_0.vtk
             
             # Try exact match
             target_name = f"hull_{int(latest_time) if latest_time % 1 == 0 else latest_time}.vtk"
             hull_file = hull_dir / target_name
             
             if not hull_file.exists():
                 # Try finding any hull file for this time
                 pass 
             
             if hull_file.exists():
                 hull = pv.read(hull_file)
                 p.add_mesh(hull, color="grey", label="Hull")
        
        p.add_title(f"Simulation: {case_dir.name} t={latest_time}")
        p.add_legend()
        p.camera_position = 'xz'
        p.camera.azimuth = 45
        p.camera.elevation = 30
        
        screenshot_path = output_dir / "viz_vtk.png"
        p.screenshot(screenshot_path)
        logging.info(f"Saved visualization to {screenshot_path}")

    except Exception as e:
        logging.error(f"Failed to visualize VTK: {e}")
